feat: downgrade swift cause gh actions1s Run swift-actions/setup-swift@v1
Error: Unexpected error, unable to continue. Please report at https://github.com/swift-actions/setup-swift/issues
Version "5.10" is not available
Stacktrace:
Error: Version "5.10" is not available
    at Object.verify (/Users/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:650:15)
    at /Users/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:397:36
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/swift-actions/setup-swift/v1/dist/index.js:377:58)